### ISSUE TITLE
invalid_password

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmyBB#38] opened 2022-11-02 10:55 UTC
I keep getting the error `invalid_password` when I try to register. I'm trying with an auto generated 100 characters password containing the characters `A-Z`, `a-z`, `0-9`, `simbols`, and `extended ASCII`. Is there a length limit or some characters that aren't allowed?

It only says `Must be at least 10 characters long.`

After trying with a 100 characters password with only the characters `A-Z`, `a-z` and `0-9` I got the error `EOF while parsing a value at line 1 column 0`.

**Comment by Nutomic** [comment] 2022-11-02 11:36
Passwords must be between 10 and 60 characters. Need to fix that message.

**Comment by Tealk** [comment] 2022-11-02 11:37
is there a reason why it is limited to 60? I would not customize the message but not limit it

**Comment by Nutomic** [comment] 2022-11-02 11:40
[Looks like there was no reason given](https://github.com/LemmyNet/lemmy/pull/1474). You can make a pull request to change it: https://github.com/LemmyNet/lemmy/blob/main/crates/api_common/src/utils.rs#L317

**Comment by JediMaster25** [comment] 2022-11-02 11:44
I've tried again twice with a 59 characters password with all character types first and then without extended ASCII, and I've gotten both errors again. First `invalid_password` and then `EOF while parsing a value at line 1 column 0`

**Comment by Nutomic** [comment] 2022-11-02 14:43
Is this on fedibb.ml? I just registered an account with a 59 char password with special characters, and it worked just fine. Logs also dont show anything. 

Tbh im really clueless what could cause this problem, and its hard to investiage without being able to reproduce it.

**Comment by JediMaster25** [comment] 2022-11-02 15:40
> Is this on fedibb.ml? I just registered an account with a 59 char password with special characters, and it worked just fine. Logs also dont show anything.
> 
> Tbh im really clueless what could cause this problem, and its hard to investiage without being able to reproduce it.

Yes. I've also just created an account without problem but I had to change username and email.

Maybe try getting the failure by using a long password and then see if the error persists after changing to a valid password. Otherwise I don't know what might have caused this.

**Comment by mu-arch** [comment] 2022-11-02 22:10
I tried to sign up to the fedibb.ml and got the `EOF while parsing a value at line 1 column 0` except my password was within the acceptable bounds. Something else might be wrong.

**Comment by Nutomic** [comment] 2022-11-02 22:13
I think i got it, this is most likely because of the rate limit. It only allows 3 signups per hour and IP, and even counts failed signup attempts (eg with invalid password). And it doesnt give any error message. Gonna have to fix this.

If you have this problem, wait for an hour before trying to register again, or use a different IP.

**Comment by JediMaster25** [comment] 2022-11-03 16:40
This 59 character password still gives an error: `Õ¼¾°3yË,o¸ãtÌÈú|ÇÁÙAøüÒI©·¤(T]/ð>æºWæ[C¤bªWöaÃÎñ·{=û³&§½K/c`

**Comment by Tealk** [comment] 2022-11-03 17:05
I think some characters are not even displayed correctly with me xD

**Comment by mu-arch** [comment] 2022-11-03 20:34
> 

I tried signing up again today and it worked.

**Comment by Nutomic** [comment] 2022-11-04 10:40
@JediMaster25 Thanks, it turns out we were using the wrong method for string length which returns the number of bytes, not chars. You will have to make your pw shorter for now (30-40 chars) until the fix is merged. https://github.com/LemmyNet/lemmy/pull/2536

**Closed** 2023-01-05 10:19 UTC
Labels: bug
